### ISSUE TITLE
Integrate into standard library?

### ISSUE THREAD

**Issue by bbarker** [vmchale/either#1]
Just a thought since [maybe is already in it](https://github.com/githwxi/ATS-Postiats/blob/master/doc/EXAMPLE/ATSLIB/libats_ML_monad_maybe.dats) (albeit as an example; maybe we could get these added in as actual library interfaces) and these are all things that come standard in the Scala standard library (for example).

**Comment by vmchale** [comment]
Might be sensible! I would definitely consider it for ATS3 :)
